# This is a basic work flow to start with github action

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name : Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: test with Pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
